/*
 * conf_application.h
 *
 * Created: 18.08.2014 15:30:56
 *  Author: magne.normann
 */ 


#ifndef CONF_APPLICATION_H_
#define CONF_APPLICATION_H_

#include <asf.h>

#define CONF_GATES_MODULE		EXT2_PWM4CTRL_MODULE

#define CONF_GATES_CHANNEL		EXT2_PWM4CTRL_0_CHANNEL
#define CONF_GATES_OUTPUT		EXT2_PWM4CTRL_0_OUTPUT
#define CONF_GATES_OUT_PIN		EXT2_PWM4CTRL_0_PIN
#define CONF_GATES_OUT_MUX		EXT2_PWM4CTRL_0_MUX



#endif /* CONF_APPLICATION_H_ */